### ISSUE TITLE
Question: Umbraco 7 Update?

### ISSUE THREAD

**Issue by rjbullock** [warrenbuckley/CWS-Umbraco-Standard-Membership#17]
Warren, have you by any chance updated this project for Umbraco 7 and the Member Service API?

**Comment by warrenbuckley** [comment]
@rjbullock unfortunately not. I need to find some time and go through all my pet projects on GitHub & BitBucket to see if any could be improved etc...

However I do not know when that will be.

**Comment by rjbullock** [comment]
Ok, bummer. Thanks anyway!
